vich_uploader:
    db_driver: orm

    metadata: 
        type: attribute

    mappings:
       recettes:
           uri_prefix: /images/recettes
           upload_destination: '%kernel.project_dir%/public/images/recettes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
